# Generated by Django 2.1.5 on 2023-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('number_str', models.CharField(max_length=200)),
                ('public_time', models.DateTimeField()),
            ],
        ),
    ]
